import { ColumnType, MenuConfig, SharePointColumnDefinition, SharePointListItem, WorkspaceConfig } from '../types';

export const INITIAL_WORKSPACES: WorkspaceConfig[] = [
  {
    id: 'ws-projects',
    name: 'Projects',
    description: 'Track corporate portfolio projects, milestones, budget allocations, and status updates.',
    iconName: 'FolderKanban',
    color: '#0284c7', // Sky Blue
    displayOrder: 1,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ws-inventory',
    name: 'Inventory & Supplies',
    description: 'Manage warehouse inventory levels, equipment tracking, reorder points, and serial numbers.',
    iconName: 'Boxes',
    color: '#16a34a', // Green
    displayOrder: 2,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ws-hr',
    name: 'HR & People Operations',
    description: 'Employee onboarding, department rosters, certification status, and training records.',
    iconName: 'Users',
    color: '#9333ea', // Purple
    displayOrder: 3,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ws-purchase',
    name: 'Procurement & Purchase',
    description: 'Purchase orders, vendor approvals, contract terms, and spend authorization workflows.',
    iconName: 'ShoppingCart',
    color: '#ea580c', // Orange
    displayOrder: 4,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ws-assets',
    name: 'IT & Fixed Assets',
    description: 'Hardware assignments, software licenses, maintenance schedules, and asset lifecycle.',
    iconName: 'Laptop',
    color: '#2563eb', // Blue
    displayOrder: 5,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ws-reports',
    name: 'Compliance & Audits',
    description: 'Quarterly compliance checks, internal audit logs, risk assessment, and policy reviews.',
    iconName: 'FileCheck',
    color: '#0d9488', // Teal
    displayOrder: 6,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
];

export const INITIAL_MENUS: MenuConfig[] = [
  {
    id: 'menu-active-projects',
    name: 'Active Projects',
    workspaceId: 'ws-projects',
    iconName: 'PlayCircle',
    displayOrder: 1,
    visible: true,
    sharePointSiteId: 'contoso.sharepoint.com,site-projects-id',
    sharePointListId: 'list-active-projects-id',
    sharePointListName: 'Active Projects List',
    primaryColumn: 'Title',
    descriptionColumn: 'Description',
    visibleColumns: [
      'Title',
      'ProjectImage',
      'ProjectManager',
      'Status',
      'Priority',
      'Budget',
      'StartDate',
      'CompletionPercentage',
      'Department',
      'RiskLevel',
      'ExpectedEndDate',
      'TotalHoursLogged',
      'CostCenter',
      'LeadArchitect',
      'Region',
      'SecurityCompliance',
      'BillingStatus',
      'ClientApproved',
      'ProjectDocURL',
      'Description',
    ],
    defaultSortColumn: 'StartDate',
    defaultSortDirection: 'desc',
    searchColumns: ['Title', 'ProjectManager', 'Status'],
    allowSearch: true,
    allowFilter: true,
    allowExport: true,
    allowFileUpload: true,
    permissions: {
      Administrator: { create: true, read: true, update: true, delete: true, export: true },
      Manager: { create: true, read: true, update: true, delete: false, export: true },
      Employee: { create: false, read: true, update: true, delete: false, export: true },
    },
    pageSize: 10,
  },
  {
    id: 'menu-completed-projects',
    name: 'Completed Projects',
    workspaceId: 'ws-projects',
    iconName: 'CheckCircle2',
    displayOrder: 2,
    visible: true,
    sharePointSiteId: 'contoso.sharepoint.com,site-projects-id',
    sharePointListId: 'list-completed-projects-id',
    sharePointListName: 'Archived Completed Projects',
    primaryColumn: 'Title',
    descriptionColumn: 'Description',
    visibleColumns: ['Title', 'ProjectManager', 'Budget', 'CompletionDate', 'ClientRating'],
    defaultSortColumn: 'CompletionDate',
    defaultSortDirection: 'desc',
    searchColumns: ['Title', 'ProjectManager'],
    allowSearch: true,
    allowFilter: true,
    allowExport: true,
    allowFileUpload: true,
    permissions: {
      Administrator: { create: true, read: true, update: true, delete: true, export: true },
      Manager: { create: false, read: true, update: false, delete: false, export: true },
      Employee: { create: false, read: true, update: false, delete: false, export: true },
    },
    pageSize: 10,
  },
  {
    id: 'menu-warehouse-stock',
    name: 'Warehouse Stock',
    workspaceId: 'ws-inventory',
    iconName: 'Package',
    displayOrder: 1,
    visible: true,
    sharePointSiteId: 'contoso.sharepoint.com,site-inventory-id',
    sharePointListId: 'list-warehouse-stock-id',
    sharePointListName: 'Central Inventory Stock List',
    primaryColumn: 'SKU',
    descriptionColumn: 'ItemName',
    visibleColumns: ['SKU', 'ItemName', 'Category', 'QuantityInStock', 'ReorderPoint', 'UnitPrice', 'WarehouseLocation'],
    defaultSortColumn: 'QuantityInStock',
    defaultSortDirection: 'asc',
    searchColumns: ['SKU', 'ItemName', 'Category', 'WarehouseLocation'],
    allowSearch: true,
    allowFilter: true,
    allowExport: true,
    allowFileUpload: true,
    permissions: {
      Administrator: { create: true, read: true, update: true, delete: true, export: true },
      Manager: { create: true, read: true, update: true, delete: true, export: true },
      Employee: { create: true, read: true, update: true, delete: false, export: true },
    },
    pageSize: 10,
  },
  {
    id: 'menu-employee-directory',
    name: 'Employee Directory',
    workspaceId: 'ws-hr',
    iconName: 'UserCheck',
    displayOrder: 1,
    visible: true,
    sharePointSiteId: 'contoso.sharepoint.com,site-hr-id',
    sharePointListId: 'list-employee-directory-id',
    sharePointListName: 'Employee Profiles',
    primaryColumn: 'FullName',
    descriptionColumn: 'JobTitle',
    visibleColumns: ['FullName', 'EmployeeID', 'Department', 'JobTitle', 'Email', 'HireDate', 'EmploymentStatus'],
    defaultSortColumn: 'FullName',
    defaultSortDirection: 'asc',
    searchColumns: ['FullName', 'EmployeeID', 'Department', 'JobTitle'],
    allowSearch: true,
    allowFilter: true,
    allowExport: true,
    allowFileUpload: false,
    permissions: {
      Administrator: { create: true, read: true, update: true, delete: true, export: true },
      Manager: { create: true, read: true, update: true, delete: false, export: true },
      Employee: { create: false, read: true, update: false, delete: false, export: true },
    },
    pageSize: 10,
  },
  {
    id: 'menu-purchase-orders',
    name: 'Purchase Orders',
    workspaceId: 'ws-purchase',
    iconName: 'FileText',
    displayOrder: 1,
    visible: true,
    sharePointSiteId: 'contoso.sharepoint.com,site-purchase-id',
    sharePointListId: 'list-purchase-orders-id',
    sharePointListName: 'Vendor Purchase Requests',
    primaryColumn: 'PONumber',
    descriptionColumn: 'VendorName',
    visibleColumns: ['PONumber', 'VendorName', 'TotalAmount', 'ApprovalStatus', 'RequestedBy', 'RequiredDate'],
    defaultSortColumn: 'RequiredDate',
    defaultSortDirection: 'desc',
    searchColumns: ['PONumber', 'VendorName', 'ApprovalStatus'],
    allowSearch: true,
    allowFilter: true,
    allowExport: true,
    allowFileUpload: true,
    permissions: {
      Administrator: { create: true, read: true, update: true, delete: true, export: true },
      Manager: { create: true, read: true, update: true, delete: false, export: true },
      Employee: { create: true, read: true, update: false, delete: false, export: true },
    },
    pageSize: 10,
  },
];

export const MOCK_SCHEMAS: Record<string, SharePointColumnDefinition[]> = {
  'list-active-projects-id': [
    { id: '1', name: 'Title', displayName: 'Project Name', type: 'Text', required: true },
    { id: '2', name: 'ProjectImage', displayName: 'Project Photo', type: 'Image', required: false },
    { id: '3', name: 'ProjectManager', displayName: 'Project Manager', type: 'Person', required: true },
    { id: '4', name: 'Status', displayName: 'Status', type: 'Choice', choices: ['Planning', 'In Progress', 'On Hold', 'Under Review'], required: true },
    { id: '5', name: 'Priority', displayName: 'Priority', type: 'Choice', choices: ['Low', 'Medium', 'High', 'Critical'], required: true },
    { id: '6', name: 'Budget', displayName: 'Budget ($)', type: 'Currency', required: true },
    { id: '7', name: 'StartDate', displayName: 'Start Date', type: 'DateTime', required: true },
    { id: '8', name: 'CompletionPercentage', displayName: 'Progress (%)', type: 'Number', required: false },
    { id: '9', name: 'Department', displayName: 'Department', type: 'Choice', choices: ['Cloud Infrastructure', 'Digital Workplace', 'Supply Chain', 'Security Ops', 'Data Analytics'], required: false },
    { id: '10', name: 'RiskLevel', displayName: 'Risk Level', type: 'Choice', choices: ['Low Risk', 'Moderate Risk', 'High Risk'], required: false },
    { id: '11', name: 'ExpectedEndDate', displayName: 'Target End Date', type: 'DateTime', required: false },
    { id: '12', name: 'TotalHoursLogged', displayName: 'Logged Hours', type: 'Number', required: false },
    { id: '13', name: 'CostCenter', displayName: 'Cost Center', type: 'Text', required: false },
    { id: '14', name: 'LeadArchitect', displayName: 'Lead Architect', type: 'Person', required: false },
    { id: '15', name: 'Region', displayName: 'Region', type: 'Choice', choices: ['North America', 'EMEA', 'APAC', 'LATAM'], required: false },
    { id: '16', name: 'SecurityCompliance', displayName: 'Compliance', type: 'Choice', choices: ['ISO27001', 'SOC2 Type II', 'HIPAA', 'FedRAMP'], required: false },
    { id: '17', name: 'BillingStatus', displayName: 'Billing State', type: 'Choice', choices: ['Invoiced', 'Milestone Based', 'Time & Materials', 'Prepaid'], required: false },
    { id: '18', name: 'ClientApproved', displayName: 'Client Approved', type: 'Boolean', required: false },
    { id: '19', name: 'ProjectDocURL', displayName: 'Spec Document', type: 'Text', required: false },
    { id: '20', name: 'Description', displayName: 'Scope & Details', type: 'Note', required: false },
  ],
  'list-completed-projects-id': [
    { id: '1', name: 'Title', displayName: 'Project Title', type: 'Text', required: true },
    { id: '2', name: 'Description', displayName: 'Final Delivery Notes', type: 'Note' },
    { id: '3', name: 'ProjectManager', displayName: 'Lead Manager', type: 'Person', required: true },
    { id: '4', name: 'Budget', displayName: 'Final Cost ($)', type: 'Currency' },
    { id: '5', name: 'CompletionDate', displayName: 'Completed On', type: 'DateTime' },
    { id: '6', name: 'ClientRating', displayName: 'CSAT Rating (1-5)', type: 'Number' },
  ],
  'list-warehouse-stock-id': [
    { id: '1', name: 'SKU', displayName: 'SKU / Part #', type: 'Text', required: true },
    { id: '2', name: 'ItemName', displayName: 'Item Description', type: 'Text', required: true },
    { id: '3', name: 'Category', displayName: 'Category', type: 'Choice', choices: ['Electronics', 'Raw Material', 'Office Hardware', 'Packaging', 'Safety Gear'], required: true },
    { id: '4', name: 'QuantityInStock', displayName: 'Stock Quantity', type: 'Number', required: true },
    { id: '5', name: 'ReorderPoint', displayName: 'Reorder Threshold', type: 'Number', required: true },
    { id: '6', name: 'UnitPrice', displayName: 'Unit Price ($)', type: 'Currency', required: true },
    { id: '7', name: 'WarehouseLocation', displayName: 'Bay / Rack', type: 'Text', required: true },
    { id: '8', name: 'InStockAlert', displayName: 'Needs Restock', type: 'Boolean' },
  ],
  'list-employee-directory-id': [
    { id: '1', name: 'FullName', displayName: 'Employee Name', type: 'Text', required: true },
    { id: '2', name: 'EmployeeID', displayName: 'Employee ID', type: 'Text', required: true },
    { id: '3', name: 'Department', displayName: 'Department', type: 'Choice', choices: ['Engineering', 'Product', 'Human Resources', 'Finance', 'Supply Chain', 'Legal'], required: true },
    { id: '4', name: 'JobTitle', displayName: 'Job Title', type: 'Text', required: true },
    { id: '5', name: 'Email', displayName: 'Corporate Email', type: 'Text', required: true },
    { id: '6', name: 'HireDate', displayName: 'Hire Date', type: 'DateTime', required: true },
    { id: '7', name: 'EmploymentStatus', displayName: 'Status', type: 'Choice', choices: ['Active Full-Time', 'Contractor', 'On Leave', 'Part-Time'], required: true },
  ],
  'list-purchase-orders-id': [
    { id: '1', name: 'PONumber', displayName: 'PO Number', type: 'Text', required: true },
    { id: '2', name: 'VendorName', displayName: 'Vendor / Supplier', type: 'Text', required: true },
    { id: '3', name: 'TotalAmount', displayName: 'Total Cost ($)', type: 'Currency', required: true },
    { id: '4', name: 'ApprovalStatus', displayName: 'Approval State', type: 'Choice', choices: ['Draft', 'Pending Manager Approval', 'Approved', 'Rejected', 'Fulfilled'], required: true },
    { id: '5', name: 'RequestedBy', displayName: 'Requested By', type: 'Person', required: true },
    { id: '6', name: 'RequiredDate', displayName: 'Required By Date', type: 'DateTime', required: true },
  ],
};

export const MOCK_ITEMS: Record<string, SharePointListItem[]> = {
  'list-active-projects-id': [
    {
      id: 'item-101',
      title: 'Cloud Migration & Azure Tenant Consolidation',
      created: '2026-01-15T10:30:00Z',
      createdBy: { displayName: 'Sarah Jenkins', email: 'sarah.j@contoso.com' },
      modified: '2026-02-01T14:20:00Z',
      modifiedBy: { displayName: 'Alex Rivera', email: 'alex.r@contoso.com' },
      fields: {
        Title: 'Cloud Migration & Azure Tenant Consolidation',
        ProjectImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=300&auto=format&fit=crop&q=80',
        ProjectManager: 'Sarah Jenkins',
        Status: 'In Progress',
        Priority: 'Critical',
        Budget: 145000,
        StartDate: '2026-01-10',
        CompletionPercentage: 65,
        Department: 'Cloud Infrastructure',
        RiskLevel: 'Low Risk',
        ExpectedEndDate: '2026-06-30',
        TotalHoursLogged: 480,
        CostCenter: 'CC-9011',
        LeadArchitect: 'Sarah Jenkins',
        Region: 'North America',
        SecurityCompliance: 'SOC2 Type II',
        BillingStatus: 'Invoiced',
        ClientApproved: true,
        ProjectDocURL: 'https://contoso.sharepoint.com/docs/azure_migration.pdf',
        Description: 'Migrate on-prem servers to Azure Cloud infrastructure and unify Active Directory domains.',
      },
      attachments: [
        { id: 'att-1', fileName: 'Architecture_Diagram_v2.pdf', url: '#', size: 2450000 },
      ],
    },
    {
      id: 'item-102',
      title: 'SharePoint Modern Intranet & Document Workflows',
      created: '2026-01-18T09:15:00Z',
      createdBy: { displayName: 'Alex Rivera', email: 'alex.r@contoso.com' },
      modified: '2026-02-03T11:00:00Z',
      modifiedBy: { displayName: 'Alex Rivera', email: 'alex.r@contoso.com' },
      fields: {
        Title: 'SharePoint Modern Intranet & Document Workflows',
        ProjectImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=300&auto=format&fit=crop&q=80',
        ProjectManager: 'Alex Rivera',
        Status: 'In Progress',
        Priority: 'High',
        Budget: 82000,
        StartDate: '2026-01-20',
        CompletionPercentage: 40,
        Department: 'Digital Workplace',
        RiskLevel: 'Moderate Risk',
        ExpectedEndDate: '2026-05-15',
        TotalHoursLogged: 320,
        CostCenter: 'CC-4022',
        LeadArchitect: 'Alex Rivera',
        Region: 'EMEA',
        SecurityCompliance: 'ISO27001',
        BillingStatus: 'Milestone Based',
        ClientApproved: true,
        ProjectDocURL: 'https://contoso.sharepoint.com/docs/intranet_spec.pdf',
        Description: 'Replace legacy network shares with dynamic SharePoint lists, sites, and Power Automate approvals.',
      },
      attachments: [],
    },
    {
      id: 'item-103',
      title: 'Mobile Supply Chain Scanner Integration',
      created: '2026-02-01T16:00:00Z',
      createdBy: { displayName: 'David Chen', email: 'david.c@contoso.com' },
      modified: '2026-02-05T08:45:00Z',
      modifiedBy: { displayName: 'David Chen', email: 'david.c@contoso.com' },
      fields: {
        Title: 'Mobile Supply Chain Scanner Integration',
        ProjectImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=300&auto=format&fit=crop&q=80',
        ProjectManager: 'David Chen',
        Status: 'Planning',
        Priority: 'Medium',
        Budget: 35000,
        StartDate: '2026-02-15',
        CompletionPercentage: 10,
        Department: 'Supply Chain',
        RiskLevel: 'Low Risk',
        ExpectedEndDate: '2026-04-30',
        TotalHoursLogged: 95,
        CostCenter: 'CC-1088',
        LeadArchitect: 'David Chen',
        Region: 'APAC',
        SecurityCompliance: 'ISO27001',
        BillingStatus: 'Time & Materials',
        ClientApproved: false,
        ProjectDocURL: 'https://contoso.sharepoint.com/docs/scanner_hardware.pdf',
        Description: 'Roll out Android handheld barcode scanners connected to central warehouse inventory list.',
      },
      attachments: [],
    },
  ],
  'list-warehouse-stock-id': [
    {
      id: 'item-201',
      title: 'SKU-88210',
      created: '2026-01-05T08:00:00Z',
      fields: {
        SKU: 'SKU-88210',
        ItemName: 'High-Speed Fiber Transceiver SFP+ 10G',
        Category: 'Electronics',
        QuantityInStock: 142,
        ReorderPoint: 50,
        UnitPrice: 185.00,
        WarehouseLocation: 'Aisle 4 - Rack 2B',
        InStockAlert: false,
      },
    },
    {
      id: 'item-202',
      title: 'SKU-10492',
      created: '2026-01-08T12:00:00Z',
      fields: {
        SKU: 'SKU-10492',
        ItemName: 'Industrial Cat6A Shielded Cables (1000ft Box)',
        Category: 'Raw Material',
        QuantityInStock: 12,
        ReorderPoint: 25,
        UnitPrice: 310.50,
        WarehouseLocation: 'Aisle 1 - Rack 5A',
        InStockAlert: true,
      },
    },
    {
      id: 'item-203',
      title: 'SKU-50211',
      created: '2026-01-12T14:30:00Z',
      fields: {
        SKU: 'SKU-50211',
        ItemName: 'Dell UltraSharp 27" 4K Monitor U2723QE',
        Category: 'Office Hardware',
        QuantityInStock: 68,
        ReorderPoint: 20,
        UnitPrice: 520.00,
        WarehouseLocation: 'Aisle 3 - Rack 1C',
        InStockAlert: false,
      },
    },
  ],
  'list-employee-directory-id': [
    {
      id: 'item-301',
      title: 'EMP-0014',
      fields: {
        FullName: 'Sarah Jenkins',
        EmployeeID: 'EMP-0014',
        Department: 'Engineering',
        JobTitle: 'Principal Cloud Architect',
        Email: 'sarah.j@contoso.com',
        HireDate: '2021-03-15',
        EmploymentStatus: 'Active Full-Time',
      },
    },
    {
      id: 'item-302',
      title: 'EMP-0029',
      fields: {
        FullName: 'Alex Rivera',
        EmployeeID: 'EMP-0029',
        Department: 'Supply Chain',
        JobTitle: 'Sr. SharePoint Operations Manager',
        Email: 'alex.r@contoso.com',
        HireDate: '2022-08-01',
        EmploymentStatus: 'Active Full-Time',
      },
    },
  ],
  'list-purchase-orders-id': [
    {
      id: 'item-401',
      title: 'PO-2026-0881',
      fields: {
        PONumber: 'PO-2026-0881',
        VendorName: 'Cisco Systems Inc.',
        TotalAmount: 48900.00,
        ApprovalStatus: 'Approved',
        RequestedBy: 'Sarah Jenkins',
        RequiredDate: '2026-02-28',
      },
    },
  ],
};
